worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream backends_multicloud {
        #Nodo 1
        server backend-multicloud-hseb.onrender.com:443;
        #Nodo 2
        server api-multicloud-nodo2.onrender.com:443;
    }

    server {
        listen 80;

        location / {
            proxy_pass https://backends_multicloud;
            
            proxy_ssl_server_name on;
            proxy_set_header Host $proxy_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}