worker_processes 1;

events {
    worker_connections 1024;
}

http {
    split_clients "${remote_addr}${msec}" $target_backend {
        50%     backend-multicloud-hseb.onrender.com;
        *       api-multicloud-nodo2.onrender.com;
    }

    server {
        listen 80;

        resolver 8.8.8.8 1.1.1.1 valid=30s;

        location / {
            proxy_pass https://$target_backend;
            
            proxy_ssl_server_name on;
            proxy_set_header Host $target_backend;
            
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}